from time import time

class Dropdown:
    '''
        A class to represent a NoJS dropdown element
        
        ...

        Attributes
        ----------
        _header : str 
            header text of dropdown element
        _body : str
            body text of dropdown element
        _id : float
            unique id tied to time of creation

        Methods
        -------
        header():
            Return header text formatted as HTML
        body():
            Return body text formatted as HTML
    '''
    def __init__(self, header, body):
        '''
            Constructs an implementation of a NoJS dropdown element
            
            Parameters
            ----------
            header : str 
                header text of dropdown element
            body : str
                body text of dropdown element
        '''
        self._header = header
        self._body = body
        self._id = time()
    
    def header(self):
        '''
            returns the section of HTML handling the header,
            ID is autogenerated to enforce uniqueness
        '''
        return \
            f'<input type="checkbox" name="collapse" id="{self._id}">\n\t<h3 class="handle">\n\t\t<label for="{self._id}">{self._header}</label>\n\t</h3>'
            
    def body(self):
        '''
            Returns the section of HTML handling the body
        '''
        return \
            f'<div class="content">\n\t\t{self._body}\n\t</div>'

    def __str__(self):
        return \
            f'<div class="cctdropdown-dropdown">\n\t{self.header()}\n\t{self.body()}\n</div>\n'