from time import time

class Dropdown:
    def __init__(self, header, body):
        self._header = header
        self._body = body
        self._id = time()
    
    def header(self):
        """
            header(self):
                Returns the section of HTML handling the header,
                ID is autogenerated to enforce uniqueness
        """
        return \
            f'<input type="checkbox" name="collapse" id="{self._id}" checked="checked">\n\t<h2 class="handle">\n\t\t<label for="{self._id}">{self._header}</label>\n\t</h2>'
            
    def body(self):
        """
            body(self):
                Returns the section of HTML handling the body
        """
        return \
            f'<div class="content">\n\t\t<p>{self._body}</p>\n\t</div>'

    def __str__(self):
        return \
            f'<section class="cctdropdown-dropdown">\n\t{self.header()}\n\t{self.body()}\n</section>'